language: python
dist: xenial

python:
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION=2.2.x
  - DJANGO_VERSION=3.0.x

install:
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"
