sudo: false

language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - pypy

env:
  - DJANGO_VERSION=1.11.x
  - DJANGO_VERSION=1.10.x
  - DJANGO_VERSION=1.9.x
  - DJANGO_VERSION=1.8.x

install:
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"

notifications:
  irc:
    channels:
      - 'irc.mozilla.org#amo-bots'
    on_success: change
    on_failure: always
