language: python
sudo: false
python:
 - "2.6"
 - "2.7"
 - "3.5"
 - "3.6"
 - "pypy"

install:
  - pip install --no-deps -r requirements.txt --use-mirrors
script: nosetests
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
