# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on: 
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10"]
        django: ["3.2.13", "4.0.4"]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    
    - name: install generic deps and django
      run: pip install --upgrade pip setuptools wheel six django~=${{ matrix.django }}
    
    - name: install package and deps
      run: pip install -e .
    
    - name: install test deps
      run: pip install -e .[tests]      
    
    - name: run tests
      run: pytest .
